### ISSUE TITLE
Absolute encoder fault detection

### ISSUE THREAD

**Issue by ghost** [FRC4607/Comp-Bot-2023#2]
https://github.com/FRC4607/Comp-Bot-2023/blob/0b28ed8a2b0fab6e64fa1af60ca25ec730427d9c/src/main/java/frc/robot/subsystems/ArmSubsystem.java#L191

There is currently only a path for the encoder to go from an initialized working state to a faulted state. There is no way to go from a faulted state to a working state. The fix is as simple as adding this transition in an else clause of the encoder health check.

**Comment by cpapplefamily** [comment]
We can look at some different ways to one shot the fault. But yes there is no reset path.
